name: Build & Push Dev Image

on:
  push:
    branches:
      - dev
    paths:
      - "**/*.go"
      - go.mod
      - go.sum
      - Dockerfile
      - .dockerignore

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: codeshelldev/gh-actions/docker-build-push@v1
        with:
          registry: ghcr.io
          token: ${{ secrets.GITHUB_TOKEN }}
          flavor: |
            latest=false
          tags: |
            type=sha
            type=raw,value=latest-dev
